name: Release

on: 
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build executables
        run: npx pkg ./node_modules/svgo 

      - name: Zip svgo-win.exe
        run: zip svgo-win.exe.zip svgo-win.exe

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "svgo-win.exe.zip"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
