name: Release

on: 
  workflow_dispatch: # Enable manual execution
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16 # Specify the Node.js version
        
      - name: npm install
        run: npm install

      - name: build executables
        run: npx pkg node_modules/svgo --targets=win

      - name: Zip svgo-win.exe
        run: zip svgo-win.exe.zip svgo-win.exe -r

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "svgo-win.exe.zip,svgo-win.exe"
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
        
        
